DROP SEQUENCE SEQ_ACESSO;

CREATE SEQUENCE SEQ_ACESSO
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE ACESSO;


CREATE TABLE ACESSO
(
  ACESSO_ID INTEGER NOT NULL,
  USUARIO_ID INTEGER NOT NULL,
  PERFIL_ID INTEGER NOT NULL,
  LOGIN_USUARIO VARCHAR2(20) NOT NULL,
  SENHA_USUARIO VARCHAR2(100) NOT NULL,
  DATA_INSERSAO timestamp DEFAULT SYSDATE,
  USUARIO_MODIFICACAO VARCHAR(10),
  DATA_MODIFICACAO timestamp DEFAULT SYSDATE,
  CONSTRAINT PK_ACESSO_ID PRIMARY KEY (ACESSO_ID),
  CONSTRAINT LOGIN_USUARIO_UNIQUE UNIQUE(LOGIN_USUARIO)
);

ALTER TABLE ACESSO
ADD CONSTRAINT FK_USUARIO_ACESSO
FOREIGN KEY (USUARIO_ID)
REFERENCES USUARIO (USUARIO_ID);

ALTER TABLE ACESSO
ADD CONSTRAINT FK_PERFIL_ACESSO
FOREIGN KEY (PERFIL_ID)
REFERENCES PERFIL (PERFIL_ID);

COMMIT;
