DROP SEQUENCE SEQ_ACESSO;

CREATE SEQUENCE SEQ_ACESSO
START WITH 1000
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE ACESSO;

CREATE TABLE ACESSO
(
  ACESSO_ID INTEGER NOT NULL,
  PESSOA_ID INTEGER NOT NULL,
  PERFIL_ID INTEGER NOT NULL,
  EMAIL VARCHAR2(50) NOT NULL,
  SENHA_PESSOA VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_ACESSO_ID PRIMARY KEY (ACESSO_ID),
  CONSTRAINT EMAIL_UNIQUE UNIQUE(EMAIL)
);

ALTER TABLE ACESSO
ADD CONSTRAINT FK_PESSOA_ACESSO
FOREIGN KEY (PESSOA_ID)
REFERENCES PESSOA (PESSOA_ID);

ALTER TABLE ACESSO
ADD CONSTRAINT FK_PERFIL_ACESSO
FOREIGN KEY (PERFIL_ID)
REFERENCES PERFIL (PERFIL_ID);

COMMIT;

SELECT * FROM ACESSO;
