DROP SEQUENCE SEQ_AUDITORIA;

CREATE SEQUENCE SEQ_AUDITORIA
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

CREATE TABLE AUDITORIA (
  AUDITORIA_ID INTEGER NOT NULL,
  DATA_HORA timestamp DEFAULT SYSDATE,
  EVENTO VARCHAR(6) NOT NULL,
  TABELA_NOME VARCHAR(50) NOT NULL,
  REGISTRO_ID INTEGER,
  PESSOA VARCHAR(50),
  DADOS_ANTIGOS JSON,
  DADOS_NOVOS JSON,
  CONSTRAINT PK_AUDITORIA_ID PRIMARY KEY (AUDITORIA_ID),
  CONSTRAINT CK_EVENTO CHECK (EVENTO IN ('INSERT', 'UPDATE', 'DELETE')) ENABLE
);

COMMIT;

SELECT * FROM AUDITORIA ORDER BY AUDITORIA_ID;