DROP SEQUENCE SEQ_DOCUMENTO_PRINCIPAL;

CREATE SEQUENCE SEQ_DOCUMENTO_PRINCIPAL
START WITH 1000
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE DOCUMENTO_PRINCIPAL;

CREATE TABLE DOCUMENTO_PRINCIPAL
(
  DOCUMENTO_PRINCIPAL_ID INTEGER NOT NULL,
  PESSOA_ID INTEGER NOT NULL,
  TIPO_DOCUMENTO_PRINCIPAL VARCHAR2(5) NOT NULL,
  NUMERO_DOCUMENTO_PRINCIPAL VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_DOCUMENTO_PRINCIPAL_ID PRIMARY KEY (DOCUMENTO_PRINCIPAL_ID),
  CONSTRAINT NUMERO_DOCUMENTO_PRINCIPAL_UNIQUE UNIQUE(NUMERO_DOCUMENTO_PRINCIPAL),
  CONSTRAINT CK_TIPO_DOCUMENTO_PRINCIPAL CHECK (TIPO_DOCUMENTO_PRINCIPAL IN ('CPF', 'CNPJ')) ENABLE
);

ALTER TABLE DOCUMENTO_PRINCIPAL
ADD CONSTRAINT FK_USUARIO_DOCUMENTO_PRINCIPAL
FOREIGN KEY (PESSOA_ID)
REFERENCES PESSOA (PESSOA_ID);

COMMIT;

SELECT * FROM DOCUMENTO_PRINCIPAL;
