DROP SEQUENCE SEQ_DOCUMENTO;

CREATE SEQUENCE SEQ_DOCUMENTO
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE DOCUMENTO;

CREATE TABLE DOCUMENTO
(
  DOCUMENTO_ID INTEGER NOT NULL,
  USUARIO_ID INTEGER NOT NULL,
  TIPO_DOCUMENTO VARCHAR2(4) NOT NULL,
  NUMERO_DOCUMENTO VARCHAR2(14) NOT NULL,
  DATA_INSERSAO timestamp DEFAULT SYSDATE,
  USUARIO_MODIFICACAO VARCHAR(10),
  DATA_MODIFICACAO timestamp DEFAULT SYSDATE,
  CONSTRAINT PK_DOCUMENTO_ID PRIMARY KEY (DOCUMENTO_ID),
  CONSTRAINT NUMERO_DOCUMENTO_UNIQUE UNIQUE(NUMERO_DOCUMENTO),
  CONSTRAINT CK_TIPO_DOCUMENTO CHECK (TIPO_DOCUMENTO IN ('CPF', 'CNPJ')) ENABLE
);

ALTER TABLE DOCUMENTO
ADD CONSTRAINT FK_USUARIO_DOCUMENTO
FOREIGN KEY (USUARIO_ID)
REFERENCES USUARIO (USUARIO_ID);

COMMIT;
SELECT * FROM DOCUMENTO;
