DROP SEQUENCE SEQ_ENDERECO;

CREATE SEQUENCE SEQ_ENDERECO
START WITH 1000
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE ENDERECO;

CREATE TABLE ENDERECO
(
  ENDERECO_ID INTEGER NOT NULL,
  PESSOA_ID INTEGER NOT NULL,
  TIPO_ENDERECO VARCHAR2(3) NOT NULL,
  CEP VARCHAR2(10) NOT NULL,
  RUA VARCHAR2(100) NOT NULL,
  NUMERO VARCHAR2(4) NOT NULL,
  COMPLEMENTO VARCHAR2(100) NOT NULL,
  BAIRRO VARCHAR2(100) NOT NULL,
  CIDADE VARCHAR2(50) NOT NULL,
  UF VARCHAR2(2) NOT NULL,
  CONSTRAINT PK_ENDERECO_ID PRIMARY KEY (ENDERECO_ID),
  CONSTRAINT CK_TIPO_ENDERECO CHECK (TIPO_ENDERECO IN ('RES', 'COM')) ENABLE
);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_PESSOA_ENDERECO
FOREIGN KEY (PESSOA_ID)
REFERENCES PESSOA (PESSOA_ID);

COMMIT;

SELECT * FROM ENDERECO;
