DELETE FROM TELEFONE WHERE TELEFONE_ID = '29';
SELECT * FROM TELEFONE ORDER BY TELEFONE_ID;


-- DELETE
DELETE FROM USUARIO_TELEFONE WHERE USUARIO_ID = '1';


-- INSERT USUARIO
INSERT INTO USUARIO (USUARIO_ID, NOME, SOBRENOME, IDADE, SEXO, EMAIL, USUARIO_MODIFICACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'João', 'Silva', DATE '1982-11-14', 'M', 'joao@example.com', 'admin');
INSERT INTO USUARIO (USUARIO_ID, NOME, SOBRENOME, IDADE, SEXO, EMAIL, USUARIO_MODIFICACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'Maria', 'Souza',  DATE '1985-06-07', 'F', 'maria@example.com', 'admin');
INSERT INTO USUARIO (USUARIO_ID, NOME, SOBRENOME, IDADE, SEXO, EMAIL, USUARIO_MODIFICACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'Carlos', 'Ferreira',  DATE '1974-09-10', 'M', 'carlos@example.com', 'admin');
INSERT INTO USUARIO (USUARIO_ID, NOME, SOBRENOME, IDADE, SEXO, EMAIL, USUARIO_MODIFICACAO) VALUES (SEQ_USUARIO.NEXTVAL, 'Ana', 'Santos',  DATE '1988-02-09', 'F', 'ana@example.com', 'admin');

SELECT * FROM USUARIO ORDER BY USUARIO_ID;


-- Inserir dados de teste na tabela DOCUMENTO usando a sequência SEQ_DOCUMENTO.NEXTVAL
INSERT INTO DOCUMENTO (DOCUMENTO_ID, USUARIO_ID, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, USUARIO_MODIFICACAO) VALUES (SEQ_DOCUMENTO.NEXTVAL, 1, 'CPF', '70204194024', 'admin');
INSERT INTO DOCUMENTO (DOCUMENTO_ID, USUARIO_ID, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, USUARIO_MODIFICACAO) VALUES (SEQ_DOCUMENTO.NEXTVAL, 2, 'CNPJ', '23580728000135', 'admin');
INSERT INTO DOCUMENTO (DOCUMENTO_ID, USUARIO_ID, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, USUARIO_MODIFICACAO) VALUES (SEQ_DOCUMENTO.NEXTVAL, 3, 'CPF', '64007782091', 'admin');
INSERT INTO DOCUMENTO (DOCUMENTO_ID, USUARIO_ID, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, USUARIO_MODIFICACAO) VALUES (SEQ_DOCUMENTO.NEXTVAL, 4, 'CNPJ', '59156987000180', 'admin');

SELECT * FROM DOCUMENTO;


-- INSERT ENDERECO
INSERT INTO ENDERECO (ENDERECO_ID, USUARIO_ID, TIPO_ENDERECO, CEP, RUA, NUMERO, COMPLEMENTO, CIDADE, UF, USUARIO_MODIFICACAO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 1, 'RES', '02146-020', 'Rua Soldado Almadio Goering', '123', 'Parque Novo Mundo', 'São Paulo', 'SP', 'admin');

INSERT INTO ENDERECO (ENDERECO_ID, USUARIO_ID, TIPO_ENDERECO, CEP, RUA, NUMERO, COMPLEMENTO, CIDADE, UF, USUARIO_MODIFICACAO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 2, 'COM', '08485-280', 'Rua Edson Danillo Dotto', '456', 'Conjunto Habitacional Santa Etelvina II', 'São Paulo', 'SP', 'admin');

INSERT INTO ENDERECO (ENDERECO_ID, USUARIO_ID, TIPO_ENDERECO, CEP, RUA, NUMERO, COMPLEMENTO, CIDADE, UF, USUARIO_MODIFICACAO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 3, 'RES', '15804-375', 'Rua das Violetas', '789', 'Jardim Pedro Borgoni', 'Catanduva', 'SP', 'admin');

INSERT INTO ENDERECO (ENDERECO_ID, USUARIO_ID, TIPO_ENDERECO, CEP, RUA, NUMERO, COMPLEMENTO, CIDADE, UF, USUARIO_MODIFICACAO) 
VALUES (SEQ_ENDERECO.NEXTVAL, 4, 'COM', '11666-800', 'Avenida Pedro Reginaldo da Costa', '135', 'Balneário dos Golfinhos', 'Caraguatatuba', 'SP', 'admin');

SELECT * FROM ENDERECO;


-- INSERT TELEFONE
INSERT INTO TELEFONE (TELEFONE_ID, USUARIO_ID, CODIGO, TIPO_TELEFONE, NUMERO_TELEFONE, USUARIO_MODIFICACAO) VALUES (SEQ_TELEFONE.NEXTVAL, 1, '55', 'RES', '11234567890', 'admin');
INSERT INTO TELEFONE (TELEFONE_ID, USUARIO_ID, CODIGO, TIPO_TELEFONE, NUMERO_TELEFONE, USUARIO_MODIFICACAO) VALUES (SEQ_TELEFONE.NEXTVAL, 2, '55', 'CEL', '11987654321', 'admin');
INSERT INTO TELEFONE (TELEFONE_ID, USUARIO_ID, CODIGO, TIPO_TELEFONE, NUMERO_TELEFONE, USUARIO_MODIFICACAO) VALUES (SEQ_TELEFONE.NEXTVAL, 3, '55', 'COM', '1112223337', 'admin');
INSERT INTO TELEFONE (TELEFONE_ID, USUARIO_ID, CODIGO, TIPO_TELEFONE, NUMERO_TELEFONE, USUARIO_MODIFICACAO) VALUES (SEQ_TELEFONE.NEXTVAL, 4, '55', 'CEL', '11444555666', 'admin');
INSERT INTO TELEFONE (TELEFONE_ID, USUARIO_ID, CODIGO, TIPO_TELEFONE, NUMERO_TELEFONE, USUARIO_MODIFICACAO) VALUES (SEQ_TELEFONE.NEXTVAL, 1, '55', 'CEL', '11938569210', 'admin');
INSERT INTO TELEFONE (TELEFONE_ID, USUARIO_ID, CODIGO, TIPO_TELEFONE, NUMERO_TELEFONE, USUARIO_MODIFICACAO) VALUES (SEQ_TELEFONE.NEXTVAL, 1, '55', 'COM', '11542365475', 'admin');

SELECT * FROM TELEFONE ORDER BY USUARIO_ID;


-- Inserindo dados na tabela ACESSO
INSERT INTO ACESSO (ACESSO_ID, USUARIO_ID, PERFIL_ID, LOGIN_USUARIO, SENHA_USUARIO, USUARIO_MODIFICACAO) VALUES (SEQ_ACESSO.NEXTVAL, 1, 1, 'joao_silva', 'qMHom-<q|@yZC]@?', 'admin');
INSERT INTO ACESSO (ACESSO_ID, USUARIO_ID, PERFIL_ID, LOGIN_USUARIO, SENHA_USUARIO, USUARIO_MODIFICACAO) VALUES (SEQ_ACESSO.NEXTVAL, 2, 2, 'maria_souza', 'b2bjP>4N.@i}H.[Z', 'admin');
INSERT INTO ACESSO (ACESSO_ID, USUARIO_ID, PERFIL_ID, LOGIN_USUARIO, SENHA_USUARIO, USUARIO_MODIFICACAO) VALUES (SEQ_ACESSO.NEXTVAL, 3, 3, 'carlos_Ferreira', 'pU,;s:rjs{n*!C.2', 'admin');
INSERT INTO ACESSO (ACESSO_ID, USUARIO_ID, PERFIL_ID, LOGIN_USUARIO, SENHA_USUARIO, USUARIO_MODIFICACAO) VALUES (SEQ_ACESSO.NEXTVAL, 4, 4, 'ana_Santos', '{a)a@|cOayKO#|K@', 'admin');
  
SELECT * FROM ACESSO ORDER BY USUARIO_ID;


-- INSERT USUARIO_X_TELEFONE
INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (6, 7); 
INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (6, 8); 
INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (6, 9); 
INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (2, 2);
INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (3, 3);
INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (4, 4);

SELECT * FROM USUARIO_TELEFONE;



SELECT u.USUARIO_ID, u.NOME, u.EMAIL, e.RUA, e.COMPLEMENTO, d.TIPO_DOCUMENTO, d.NUMERO_DOCUMENTO  FROM USUARIO u
INNER JOIN ENDERECO e
ON u.USUARIO_ID = e.USUARIO_ID
INNER JOIN DOCUMENTO d
ON u.USUARIO_ID = d.USUARIO_ID
WHERE u.USUARIO_ID = 4;


