DROP TABLE ACESSO_PERFIL; 

CREATE TABLE ACESSO_PERFIL
(
  ACESSO_ID INTEGER NOT NULL,
  ACESSO_PERFIL_ID INTEGER NOT NULL,
  PRIMARY KEY (ACESSO_ID, ACESSO_PERFIL_ID),
  FOREIGN KEY (ACESSO_ID) REFERENCES ACESSO (ACESSO_ID),
  FOREIGN KEY (ACESSO_PERFIL_ID) REFERENCES PERFIL (PERFIL_ID)
);