DROP SEQUENCE SEQ_PERFIL;

CREATE SEQUENCE SEQ_PERFIL
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE PERFIL;

CREATE TABLE PERFIL
(
  PERFIL_ID INTEGER NOT NULL,
  SIG_PERFIL VARCHAR2(15) NOT NULL,
  NOME_PERFIL VARCHAR2(30) NOT NULL,
  DESCRICAO VARCHAR2(50) NOT NULL,
  USUARIO_INSERCAO VARCHAR(10),
  DATA_INSERSAO timestamp DEFAULT SYSDATE,
  USUARIO_MODIFICACAO VARCHAR(10),
  DATA_MODIFICACAO timestamp DEFAULT SYSDATE,
  CONSTRAINT PK_PERFIL_PERMISSAOTELA PRIMARY KEY (PERFIL_ID)
);

INSERT INTO PERFIL (PERFIL_ID, NOME_PERFIL, SIG_PERFIL, DESCRICAO) VALUES (SEQ_PERFIL.NEXTVAL, 'Administrador', 'ADM', 'Perfil de administrador do sistema');
INSERT INTO PERFIL (PERFIL_ID, NOME_PERFIL, SIG_PERFIL, DESCRICAO) VALUES (SEQ_PERFIL.NEXTVAL, 'Basico', 'BSC', 'Perfil basico do sistema');
INSERT INTO PERFIL (PERFIL_ID, NOME_PERFIL, SIG_PERFIL, DESCRICAO) VALUES (SEQ_PERFIL.NEXTVAL, 'Medio', 'MDO', 'Perfil médio do sistema');
INSERT INTO PERFIL (PERFIL_ID, NOME_PERFIL, SIG_PERFIL, DESCRICAO) VALUES (SEQ_PERFIL.NEXTVAL, 'Master', 'MST', 'Perfil master do sistema');

SELECT * FROM PERFIL;