DROP SEQUENCE SEQ_PERMISSAOTELA;

CREATE SEQUENCE SEQ_PERMISSAOTELA
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE PERMISSAOTELA;

CREATE TABLE PERMISSAOTELA
(
  PERMISSAOTELA_ID INTEGER NOT NULL,
  NOME_PERMISSAO VARCHAR2(15) NOT NULL,
  DESCRICAO VARCHAR2(50) NOT NULL,
  USUARIO_INSERCAO VARCHAR(10),
  DATA_INSERSAO timestamp DEFAULT SYSDATE,
  USUARIO_MODIFICACAO VARCHAR(10),
  DATA_MODIFICACAO timestamp DEFAULT SYSDATE,
  CONSTRAINT PK_PERMISSAOTELA_ID PRIMARY KEY (PERMISSAOTELA_ID),
  CONSTRAINT DESCRICAO_UNIQUE UNIQUE(DESCRICAO)
);

INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'CADASTRAR', 'Permissão para cadastrar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'EDITAR', 'Permissão para editar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'EXCLUIR', 'Permissão para excluir dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'CONSULTAR', 'Permissão para consultar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'IMPRIMIR', 'Permissão para imprimir dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'EXPORTAR', 'Permissão para exportar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'IMPORTAR', 'Permissão para importar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'GERAR', 'Permissão para gerar relatórios na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'ANALISAR', 'Permissão para analisar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'VALIDAR', 'Permissão para validar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'AUTORIZAR', 'Permissão para autorizar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'NEGAR', 'Permissão para negar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'APROVAR', 'Permissão para aprovar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'REPROVAR', 'Permissão para reprovar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'CANCELAR', 'Permissão para cancelar dados na tela');
INSERT INTO PERMISSAOTELA (PERMISSAOTELA_ID, NOME_PERMISSAO, DESCRICAO) VALUES (SEQ_PERMISSAOTELA.NEXTVAL, 'ACESSAR', 'Permissão para acessar a tela');


SELECT * FROM PERMISSAOTELA;