DROP SEQUENCE SEQ_PESSOA_JURIDICA;

CREATE SEQUENCE SEQ_PESSOA_JURIDICA
START WITH 1000
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE PESSOA_JURIDICA;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';

CREATE TABLE PESSOA_JURIDICA
(
  PESSOA_JURIDICA_ID INTEGER NOT NULL,
  DOCUMENTO_PRINCIPAL_ID INTEGER NOT NULL,
  NOME_COMERCIAL VARCHAR2(50) NOT NULL,
  DATA_CONSTITUICAO DATE NOT NULL,
  TIPO_INSCRICAO VARCHAR2(4) NOT NULL,
  NUMERO_INSCRICAO VARCHAR2(20) NOT NULL,
  NATUREZA_JURIDICA VARCHAR2(255) NOT NULL,
  RAMO_ATIVIDADE VARCHAR2(255) NOT NULL,
  OBJETIVO_SOCIAL VARCHAR2(255),
  CONSTRAINT PK_PESSOA_JURIDICA_ID PRIMARY KEY (PESSOA_JURIDICA_ID),
  CONSTRAINT NUMERO_INSCRICAO_UNIQUE UNIQUE(NUMERO_INSCRICAO),
  CONSTRAINT CK_TIPO_INSCRICAO CHECK (TIPO_INSCRICAO IN ('MEI', 'EI','LTDA', 'SLU', 'SS', 'SA')) ENABLE
);

ALTER TABLE PESSOA_JURIDICA
ADD CONSTRAINT FK_DOCUMENTOS_PRINCIPAL_PESSOA_JURIDICA
FOREIGN KEY (DOCUMENTO_PRINCIPAL_ID)
REFERENCES DOCUMENTO_PRINCIPAL (DOCUMENTO_PRINCIPAL_ID);

COMMIT;

SELECT * FROM PESSOA_JURIDICA ORDER BY PESSOA_JURIDICA_ID;


