DROP SEQUENCE SEQ_PESSOA;

CREATE SEQUENCE SEQ_PESSOA
START WITH 1000
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE PESSOA;

CREATE TABLE PESSOA
(
  PESSOA_ID INTEGER NOT NULL,
  NOME VARCHAR2(50) NOT NULL,
  ATIVO CHAR(1) NOT NULL,
  CONSTRAINT PK_PESSOA_ID PRIMARY KEY (PESSOA_ID),
  CONSTRAINT CK_PESSOA_ATIVO CHECK (ATIVO IN ('S', 'N')) ENABLE
);

COMMIT;

SELECT * FROM PESSOA ORDER BY PESSOA_ID;