DROP SEQUENCE SEQ_PESSOA_FISICA;

CREATE SEQUENCE SEQ_PESSOA_FISICA
START WITH 1000
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE PESSOA_FISICA;

CREATE TABLE PESSOA_FISICA
(
  PESSOA_FISICA_ID INTEGER NOT NULL,
  DOCUMENTO_PRINCIPAL_ID INTEGER NOT NULL,
  SOBRENOME VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_PESSOA_FISICA_ID PRIMARY KEY (PESSOA_FISICA_ID)
);

ALTER TABLE PESSOA_FISICA
ADD CONSTRAINT FK_DOCUMENTOS_PRINCIPAL_PESSOA_FISICA
FOREIGN KEY (DOCUMENTO_PRINCIPAL_ID)
REFERENCES DOCUMENTO_PRINCIPAL (DOCUMENTO_PRINCIPAL_ID);

COMMIT;

SELECT * FROM PESSOA_FISICA ORDER BY PESSOA_FISICA_ID;

