DROP SEQUENCE SEQ_TELEFONE;

CREATE SEQUENCE SEQ_TELEFONE
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE TELEFONE;

CREATE TABLE TELEFONE
(
  TELEFONE_ID INTEGER NOT NULL,
  USUARIO_ID INTEGER NOT NULL,
  CODIGO VARCHAR2(2) NOT NULL,
  TIPO_TELEFONE VARCHAR2(12) NOT NULL,
  NUMERO_TELEFONE VARCHAR2(12) NOT NULL,
  DATA_INSERSAO timestamp DEFAULT SYSDATE,
  USUARIO_MODIFICACAO VARCHAR(10),
  DATA_MODIFICACAO timestamp DEFAULT SYSDATE,
  CONSTRAINT PK_TELEFONE_ID PRIMARY KEY (TELEFONE_ID),
  CONSTRAINT CK_TIPO_TELEFONE CHECK (TIPO_TELEFONE IN ('RES', 'CEL', 'COM')) ENABLE
);

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_USUARIO_TELEFONE
FOREIGN KEY (USUARIO_ID)
REFERENCES USUARIO (USUARIO_ID);


COMMIT;