DROP SEQUENCE SEQ_TELEFONE;

CREATE SEQUENCE SEQ_TELEFONE
START WITH 1000
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE TELEFONE;

CREATE TABLE TELEFONE
(
  TELEFONE_ID INTEGER NOT NULL,
  CODIGO VARCHAR2(2) NOT NULL,
  TIPO_TELEFONE VARCHAR2(12) NOT NULL,
  NUMERO_TELEFONE VARCHAR2(12) NOT NULL,
  CONSTRAINT PK_TELEFONE_ID PRIMARY KEY (TELEFONE_ID),
  CONSTRAINT CK_TIPO_TELEFONE CHECK (TIPO_TELEFONE IN ('RES', 'CEL', 'COM')) ENABLE
);

COMMIT;

SELECT * FROM TELEFONE;