DROP TABLE USUARIO_TELEFONE; 

CREATE TABLE USUARIO_TELEFONE
(
  USUARIO_ID INTEGER NOT NULL,
  TELEFONE_USUARIO_ID INTEGER NOT NULL,
  PRIMARY KEY (USUARIO_ID, TELEFONE_USUARIO_ID),
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (USUARIO_ID),
  FOREIGN KEY (TELEFONE_USUARIO_ID) REFERENCES TELEFONE (TELEFONE_ID)
);

INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (1, 1); 
INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (1, 5); 
INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (2, 2);
INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (3, 3);
INSERT INTO USUARIO_TELEFONE (USUARIO_ID, TELEFONE_USUARIO_ID) VALUES (4, 4);

SELECT * FROM USUARIO_TELEFONE;