DROP TABLE USUARIO_AUDITORIA; 

CREATE TABLE USUARIO_AUDITORIA
(
  USUARIO_ID INTEGER NOT NULL,
  AUDITORIA_USUARIO_ID INTEGER NOT NULL,
  PRIMARY KEY (USUARIO_ID, AUDITORIA_USUARIO_ID),
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID),
  FOREIGN KEY (AUDITORIA_USUARIO_ID) REFERENCES AUDITORIA (AUDITORIA_ID)
);


COMMIT;