DROP SEQUENCE SEQ_USUARIO;

CREATE SEQUENCE SEQ_USUARIO
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOCYCLE;

DROP TABLE USUARIO;

CREATE TABLE USUARIO
(
  USUARIO_ID INTEGER NOT NULL,
  PERFIL_ID INTEGER NOT NULL,
  NOME VARCHAR2(20) NOT NULL,
  SOBRENOME VARCHAR2(50) NOT NULL,
  EMAIL VARCHAR2(30) NOT NULL,
  DATA_INSERSAO timestamp DEFAULT SYSDATE,
  USUARIO_MODIFICACAO VARCHAR(10),
  DATA_MODIFICACAO timestamp DEFAULT SYSDATE,
  CONSTRAINT PK_USUARIO_ID PRIMARY KEY (USUARIO_ID),
  CONSTRAINT EMAIL_UNIQUE UNIQUE(EMAIL)
);

ALTER TABLE USUARIO
ADD CONSTRAINT FK_USUARIO_PERFIL
FOREIGN KEY (PERFIL_ID)
REFERENCES PERFIL (PERFIL_ID);


INSERT INTO USUARIO (USUARIO_ID, PERFIL_ID, NOME, SOBRENOME, EMAIL, USUARIO_MODIFICACAO) VALUES (SEQ_USUARIO.NEXTVAL, 1, 'João', 'Silva', 'joao@example.com', 'admin');
INSERT INTO USUARIO (USUARIO_ID, PERFIL_ID, NOME, SOBRENOME, EMAIL, USUARIO_MODIFICACAO) VALUES (SEQ_USUARIO.NEXTVAL, 2, 'Maria', 'Souza', 'maria@example.com', 'admin');
INSERT INTO USUARIO (USUARIO_ID, PERFIL_ID, NOME, SOBRENOME, EMAIL, USUARIO_MODIFICACAO) VALUES (SEQ_USUARIO.NEXTVAL, 3, 'Carlos', 'Ferreira', 'carlos@example.com', 'admin');
INSERT INTO USUARIO (USUARIO_ID, PERFIL_ID, NOME, SOBRENOME, EMAIL, USUARIO_MODIFICACAO) VALUES (SEQ_USUARIO.NEXTVAL, 4, 'Ana', 'Santos', 'ana@example.com', 'admin');


SELECT * FROM USUARIO;