DROP TABLE USUARIO_TELEFONE; 

CREATE TABLE USUARIO_TELEFONE
(
  USUARIO_ID INTEGER NOT NULL,
  TELEFONE_USUARIO_ID INTEGER NOT NULL,
  PRIMARY KEY (USUARIO_ID, TELEFONE_USUARIO_ID),
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID),
  FOREIGN KEY (TELEFONE_USUARIO_ID) REFERENCES TELEFONE (TELEFONE_ID)
);


COMMIT;